### ISSUE TITLE
Ctrl + M does not open the menu

### ISSUE THREAD

**Issue by Danchyg1337** [DrChaleceCume/mnee#1]
No commits at all work properly. Only the legacy version downloaded from here (https://modworkshop.net/mod/37673) can open the menu. Is there a specific installation or is it a bug?

**Comment by re-coilless** [comment]
How the fuck am I noticing this only now

**Comment by re-coilless** [comment]
Alright, I did some investigating: there's quite a number of similar reports and it seems all of them are related to controller in some way. Am I correct in this assumption and can you provide more info related to specifics, as I'm unable to reproduce the bug?

**Comment by Danchyg1337** [comment]
With trial and error it turned out that I had to use beta-branch version of the game. I don't remember by now either it was my blindness or it wasn't specified in any place. If this is intended then there is no issue at all

**Comment by re-coilless** [comment]
I remember mentioning beta-only state on the steam page but all my gits are rather all over the place regarding the readme. Thanks for getting back to me and I really gotta do something about repo presentation at some point.

**Comment by r0levrai** [comment]
A few additional infos:
- the mod folder must be named exactly `mnee`
- for non-english keyboards, opening the mod menu is done by pressing where `Ctrl-M` would be on a english keyboard
- it seems to work on the non-beta branch now (Noita Build Aug 12 2024, mnee 12ac7196dd53b61619597d718f1ababc84f53cfc)

Also, if you use this for the Couch Coop mod (offtopic but will surely help future me):
- coop mod folder must be named exactly `CouchCoOp` (I'm new to noita modding and run the game though GoG where you have to download steam workshop-exclusive mods using `SteamCmd` which gives you another folder name ; so I had no idea this was needed, until running `noita_dev.exe` and seeing the errors  about said hardcoded paths not found)
- if the `Q` and `E` keys don't work: for me, they were bound to two keys each and needed to be rebinded in the mnee's `Ctrl-M` menu
- if one out of two inventory bars is empty, reboot the game
